# Generated by Django 3.1.6 on 2021-03-10 18:09

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_profile', '0002_auto_20210310_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=imagekit.models.fields.ProcessedImageField(upload_to='post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_pic',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
