# Generated by Django 3.1.6 on 2021-03-15 08:52

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_profile', '0004_auto_20210311_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_pic',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='/static/images/default.png', null=True, upload_to='photos'),
        ),
    ]
