# Generated by Django 3.1.6 on 2021-05-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_profile', '0007_auto_20210315_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='room',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
